import type { Metadata } from "next";

// Componentes
import "./globals.css";
import Header from "./components/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-[url(/images/img2.jpg)] bg-cover">
        <Header/>
        {children}
      </body>
    </html>
  );
}
